# Generated by Django 6.0.4 on 2026-05-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('chat', '0002_chatroom_initiated'),
    ]

    operations=[
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
