# Generated by Django 6.0.4 on 2026-05-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('chat', '0003_message_is_read'),
    ]

    operations=[
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
    ]
