# Generated by Django 6.0.4 on 2026-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('chat', '0004_message_file'),
    ]

    operations=[
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
