# Generated by Django 6.0.4 on 2026-05-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('chat', '0005_chatroom_deleted_by_manager_chatroom_deleted_by_user'),
    ]

    operations=[
        migrations.AddField(
            model_name='chatroom',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
