# Generated by Django 6.0.4 on 2026-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_is_closed_chatroom_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
