# Generated by Django 6.0.4 on 2026-04-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0001_initial'),
    ]

    operations=[
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
