# Generated by Django 6.0.4 on 2026-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0002_application_resume'),
    ]

    operations=[
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interviewing', 'Interviewing'), ('shortlisted', 'Shortlisted'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
