# Generated by Django 6.0.4 on 2026-04-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0003_alter_application_status'),
        ('users', '0005_resume_extracted_text'),
    ]

    operations=[
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.resume'),
        ),
    ]
