# Generated by Django 6.0.4 on 2026-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0004_alter_application_resume'),
    ]

    operations=[
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.FloatField(default=0.0),
        ),
    ]
