# Generated by Django 6.0.4 on 2026-05-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0005_application_ats_score'),
    ]

    operations=[
        migrations.AddField(
            model_name='application',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
