# Generated by Django 6.0.4 on 2026-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0007_interviewreview'),
    ]

    operations=[
        migrations.RenameField(
            model_name='interviewreview',
            old_name='rating',
            new_name='interviewer_behavior',
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='overall_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='process_clarity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='interviewreview',
            name='technical_difficulty',
            field=models.IntegerField(default=5),
        ),
    ]
