# Generated by Django 6.0.4 on 2026-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0008_rename_rating_interviewreview_interviewer_behavior_and_more'),
    ]

    operations=[
        migrations.AddField(
            model_name='interviewreview',
            name='culture_environment',
            field=models.IntegerField(default=5),
        ),
    ]
