# Generated by Django 6.0.4 on 2026-05-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0009_interviewreview_culture_environment'),
    ]

    operations=[
        migrations.RenameField(
            model_name='interviewreview',
            old_name='culture_environment',
            new_name='on_boarding_experience',
        ),
    ]
