# Generated by Django 6.0.4 on 2026-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('applications', '0010_rename_culture_environment_interviewreview_on_boarding_experience'),
    ]

    operations=[
        migrations.AddField(
            model_name='application',
            name='screening_answers',
            field=models.JSONField(default=dict),
        ),
    ]
