# Generated by Django 6.0.4 on 2026-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_application_screening_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assessment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interviewing', 'Interviewing'), ('shortlisted', 'Shortlisted'), ('assessment_pending', 'Assessment Pending'), ('assessment_completed', 'Assessment Completed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
