# Generated by Django 6.0.4 on 2026-05-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_assessment_completed_and_more'),
        ('jobs', '0007_job_experience_level_job_is_draft_job_job_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('shortlisted', 'Shortlisted'), ('assessment_pending', 'Assessment Pending'), ('assessment_completed', 'Assessment Completed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
        migrations.CreateModel(
            name='SavedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('manager', 'candidate')},
            },
        ),
    ]
