# Generated by Django 6.0.4 on 2026-05-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedApplicant',
        ),
    ]
