# Generated by Django 6.0.4 on 2026-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('jobs', '0001_initial'),
    ]

    operations=[
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
