# Generated by Django 6.0.4 on 2026-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('jobs', '0002_alter_job_salary'),
    ]

    operations=[
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
