# Generated by Django 6.0.4 on 2026-05-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('jobs', '0003_job_deadline'),
    ]

    operations=[
        migrations.AddField(
            model_name='job',
            name='min_ats_score',
            field=models.IntegerField(default=50),
        ),
    ]
