# Generated by Django 6.0.4 on 2026-05-07 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('jobs', '0004_job_min_ats_score'),
    ]

    operations=[
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('textarea', 'Textarea')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='jobs.job')),
            ],
        ),
    ]
