# Generated by Django 6.0.4 on 2026-05-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('jobs', '0005_jobquestion'),
    ]

    operations=[
        migrations.AddField(
            model_name='jobquestion',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
