# Generated by Django 6.0.4 on 2026-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('users', '0004_remove_user_resume_resume'),
    ]

    operations=[
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
