# Generated by Django 6.0.4 on 2026-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies=[
        ('users', '0005_resume_extracted_text'),
    ]

    operations=[
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
