# Generated by Django 6.0.4 on 2026-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_certifications_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
