# Generated by Django 6.0.4 on 2026-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='type',
            field=models.CharField(default='resume', max_length=50),
        ),
    ]
